CI: build release

diff --git a/.github/workflows/gem-push.yml b/.github/workflows/gem-push.yml
--- a/.github/workflows/gem-push.yml
+++ b/.github/workflows/gem-push.yml
@@ -80,29 +80,22 @@ jobs:
           # gem push *.gem
         fi
         echo "Check for existing release tag"
-        response=$(curl --write-out '%{http_code}' --silent --output /dev/null -u ${{ secrets.GITHUB_TOKEN }} "https://api.github.com/repos/${{ github.repository }}/releases/tags/$JARBLER_RELEASE")
-        if [[ $response -eq 200 ]]; then
-          echo "RELEASE_TAG_EXISTS=true" >> $GITHUB_ENV
+        gh release view $JARBLER_RELEASE -R ${{ github.repository }}
+        if [[ $? -eq 0 ]]; then
           echo "Github release tag $JARBLER_RELEASE already exists"
         else
-          echo "RELEASE_TAG_EXISTS=false" >> $GITHUB_ENV
           echo "Github release tag $JARBLER_RELEASE does not exist yet"
+          gh release create $JARBLER_RELEASE './jarbler-$JARBLER_RELEASE.gem#jarbler-$JARBLER_RELEASE.gem: use also "gem install jarbler"' --notes "Continuous development" --title "Jarbler $JARBLER_RELEASE"
+          if [ $? -eq 0 ]; then
+            echo "Release created"
+          else
+            echo "gh release create failed"
+            exit 1
+          fi
         fi
         ls -l
       # env:
         # GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
-
-    - name: Create Release
-      id: create_release
-      if: ${{ env.RELEASE_TAG_EXISTS }} != "true"
-      uses: actions/create-release@v1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
-      with:
-        tag_name: ${{ env.JARBLER_RELEASE }}
-        release_name: Jarbler ${{ env.JARBLER_RELEASE }}
-        draft: false
-        prerelease: false
 
     - name: Put gem file into artifact
       if: always()
